<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_jwt_authentication.security.authentication.entry_point.api' shared service.

@trigger_error('The "lexik_jwt_authentication.security.authentication.entry_point.api" service is deprecated since LexikJWTAuthenticationBundle version 2.0 and will be removed in 3.0', E_USER_DEPRECATED);

return $this->services['lexik_jwt_authentication.security.authentication.entry_point.api'] = new \Lexik\Bundle\JWTAuthenticationBundle\Security\Http\EntryPoint\JWTEntryPoint();
