<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA1xxopf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA1xxopf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerA1xxopf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerA1xxopf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerA1xxopf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'A1xxopf',
    'container.build_id' => 'd444561a',
    'container.build_time' => 1534435721,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerA1xxopf');
