<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVuagx3d\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVuagx3d/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVuagx3d.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVuagx3d\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVuagx3d\appProdProjectContainer(array(
    'container.build_hash' => 'Vuagx3d',
    'container.build_id' => '4efe94fd',
    'container.build_time' => 1534424511,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVuagx3d');
