<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAvtziiz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAvtziiz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAvtziiz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAvtziiz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAvtziiz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Avtziiz',
    'container.build_id' => 'b7c92eb2',
    'container.build_time' => 1534446273,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAvtziiz');
