<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7y1t8gw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7y1t8gw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7y1t8gw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7y1t8gw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7y1t8gw\appDevDebugProjectContainer(array(
    'container.build_hash' => '7y1t8gw',
    'container.build_id' => 'dfd48458',
    'container.build_time' => 1534444809,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7y1t8gw');
